services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
     - .:/frontend
     - ./node_modules:/frontend/node_modules
    env_file:
     - .env
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm start 