services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm start

  api:
    build: ./server
    ports:
      - "5002:5000"  # Exposing Flask on port 5001 of the host
    volumes:
      - ./server:/server
    environment:
      FLASK_ENV: production
      LISTEN_PORT: 5000
    command: python index1.py
